### ISSUE TITLE
搜索按钮有效，但是下载按钮无效 可以修复吗

### ISSUE THREAD

**Issue by zzhcx** [LanluZ/Diyibanzhu-Download#2]

**Comment by LanluZ** [comment]
**描述**

截止于今日,下载按钮为有效状态

在选中章节后点击下载需要等待一段时间

**版本信息**

Chrome 127.0.6533.89

**预览**
![image](https://github.com/user-attachments/assets/69e7ab65-6d0e-437f-bf9f-cb15e6b01b8b)
