### ISSUE TITLE
脚本使用问题

### ISSUE THREAD

**Issue by inSANITYxxxx** [LanluZ/Diyibanzhu-Download#3]
大大你好，不好意思，我不会python，这个扩展在油猴里下载了，但是我点不了下载按钮是什么情况啊，是不是还需要按照那个“后处理程序”里面的步骤再去配置啊？但是我看不太懂，有详细一点的吗？
![image](https://github.com/user-attachments/assets/2714921f-c28c-4b50-ad53-d63ca808b9fb)
![image](https://github.com/user-attachments/assets/a17f1cdb-21bf-4469-958d-3a810bf98cc9)

**Comment by LanluZ** [comment]
Ciallo～(∠・▽< )⌒☆

**关于点不了下载按钮**

1. 是因为并没有给按钮设置 鼠标悬停 样式为 手型, 所以看上去无法点击,实际可以点击

**请按此方法进行重新操作**

1. 选中指定章节
2. 按F12打开 开发者-控制台
3. 等待下载输出

![image](https://github.com/user-attachments/assets/f9a86b99-4cf4-477d-8785-5df84d81e154)

![image](https://github.com/user-attachments/assets/f54bc4cb-d71f-4f68-abcf-62ef77fb47d0)

如果问题依然存在请提供更详细信息

**关于后处理程序**

因为网站反爬虫应对方案包括但不限于

1. 字体替换
2. 文字图片

所以后处理程序采用OCR进行文本识别,识别结果会合并为TXT文件
