### ISSUE TITLE
工作目录错误

### ISSUE THREAD

**Issue by Murasamer** [LanluZ/Diyibanzhu-Download#4]
大佬您好，我已经安装了requirement.txt中的模块，但是后处理时运行main.py显示没有名称为 'ocr' 的模块，请问这是怎么回事，poppler 与 PaddleOCR-json都放在了ocr文件夹下，PaddleOCR-json下载的是[PaddleOCR-json_v1.4.1_windows_x64.7z]，poppler 下载的是[poppler-24.09.0.tar.xz]，都是解压后的。

**Comment by Murasamer** [comment]
它生成了一个image文件夹，但是里面什么也没有，然后python提示找不到文件
![image](https://github.com/user-attachments/assets/09529eab-e943-4161-a315-7ee3c36f64a5)

**Comment by LanluZ** [comment]
从您的描述上看为工作目录错误

由于是在目录 `/ocr/` 下 运行了 `main.py` 程序, 程序无法找到 `/ocr/ocr/` 目录

可以尝试以下多种解决方案:

1. 在 `/` 目录下 运行 `python ./ocr/main.py`

2. 修改 `main.py` 中相关代码, 再次按原来方式运行

      ```python
      import ocr.api.tbpu as tbpu
      from ocr.api.PPOCR_api import GetOcrApi
      ```
      修改为
      ```python
      import api.tbpu as tbpu
      from api.PPOCR_api import GetOcrApi
      ```

3. 设置项目IDE 运行 `main.py` 设置工作目录为 `/`

**Comment by Murasamer** [comment]
![image](https://github.com/user-attachments/assets/914f9408-5e77-43b4-8d08-8735ca7c1fb1)这是没有转换为图片的意思吗

**Comment by LanluZ** [comment]
> 这是没有转换为图片的意思吗

@Murasamer 没有识别到poppler, 请将 poppler程序目录 放在对应目录

**Comment by Murasamer** [comment]
![image](https://github.com/user-attachments/assets/f77e2b5a-9242-498f-92d4-89e739f4d254)
这里显示poppler的路径包含Library/bin，但是我下载的文件中没有这些文件，是我下错了吗
![image](https://github.com/user-attachments/assets/dcc16503-ed21-4023-b68f-6ff143bcf595)

**Comment by Murasamer** [comment]
大佬您好，我的问题已经解决，感谢大佬耐心细致的解答

**Comment by LanluZ** [comment]
感谢您的提问❤

存在部分文件目录未自动创建问题和README超链接指向不明确相关问题

现已得到 [1.0.1版本](https://github.com/LanluZ/Diyibanzhu-Download/releases/tag/1.0.1) 修复
